apiVersion: v1
kind: Service
metadata:
  name: ruoyi-exporter-external
  namespace: monitoring
  labels:
    app: ruoyi-exporter # Service 自身的标签
spec:
  type: NodePort
  # 添加选择器，关联标签为 app: ruoyi-exporter 的 Pod
  selector:
    app: ruoyi-exporter 
  ports:
    - name: http-metrics
      port: 30012
      targetPort: 30012
      protocol: TCP
      # 如果需要固定 NodePort，可以取消下面这一行的注释
      # nodePort: 32298